### ISSUE TITLE
Readme details I noticed while having a first try 

### ISSUE THREAD

**Issue by Adam-it** [mgwojciech/mgwdev-m365-helpers#1]
## 1️⃣ of all 

Good job 💪 I only had a really quick overview on this with a simple spfx webpart but it seems to work pretty sweet 👍. You rock 🤩.

### in the GraphODataPagedDataProvider example 
```
let spfxGraphClient = this.context.aadHttpClientFactory.getClient('https://graph.microsoft.com');

let client = new BatchGraphClient(new SPFxGraphHttpClient(spfxGraphClient));
let pagedProvider = new GraphODataPagedDataProvider<any>(batchClient, "https://graph.microsoft.com/v1.0/users");
pagedProvider.pageSize = 10;

let users = await pagedProvider.getData();
let allUsers = pagedProvider.allItemsCount;
if(pagedProvider.isNextPageAvailable()){
    let nextPage = await pagedProvider.getNextPage();
}
if(pagedProvider.isPreviousPageAvailable()){
    let previousPage = await pagedProvider.getPreviousPage();
}
```
I think it should be `let batchClient = new BatchGraphClient(new SPFxGraphHttpClient(spfxGraphClient));` right 🤔?

### in the spfx example 
```
let spfxGraphClient = this.context.aadHttpClientFactory.getClient('https://graph.microsoft.com');

let client = new BatchGraphClient(new SPFxGraphHttpClient(spfxGraphClient));

let [me, photo, presence] = await Promise.all([
    client.get("https://graph.microsoft.com/v1.0/me"),
    client.get("https://graph.microsoft.com/v1.0/me/presence"),
    client.get("https://graph.microsoft.com/v1.0/me/photo/$value")
])
```

If I am not mistaking the [aadHttpClientFactory.getClient()](https://docs.microsoft.com/en-us/javascript/api/sp-http/aadhttpclientfactory?view=sp-typescript-latest#@microsoft-sp-http-aadhttpclientfactory-getclient-member(1)) returns a `Promise<AadHttpClient>` so I think we should `await` it like 
`let spfxGraphClient = await this.context.aadHttpClientFactory.getClient('https://graph.microsoft.com');`

**Comment by mgwojciech** [comment]
Yes, You are right. I'll fix that soon :)
This is what happens when You create a docs from two different samples ;)

**Comment by Adam-it** [comment]
also did you consider exporting every module in the root index.js 🤔. Currently If I want to use `SPFxGraphHttpClient` I need to retrieve it from the inner structure of you lib like
```
import { SPFxGraphHttpClient } from 'mgwdev-m365-helpers/lib/dal/http';
```
This is quite ok but in the end it means I need to be aware of the package structure.

I wonder if it would be better if we could just do 
```
import { SPFxGraphHttpClient } from 'mgwdev-m365-helpers';
```

**Comment by mgwojciech** [comment]
Hi - I fixed the readme - that's for noticing that :)
About imports - I will for sure handle that for 1.0.0. I want to figure out how I can have both  es5 and commonjs libs and make relevant distribution bundle at compile time.
